site_name: 📖 Samudra
site_url: https://thaza-kun.github.io/samudra/
repo_url: https://github.com/Thaza-Kun/samudra
repo_name: Samudra - Github
theme:
  name: material
  features:
    - navigation.tabs
watch:
  - samudra/
plugins:
  - search
  - gen-files:
      scripts:
        - docs_from_source.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      # handlers:
      #   python:
      #     paths: ["."]

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # NAV


nav:
  - Home:
      - Pengenalan: index.md
      - Teras: teras.md
      - Aplikasi: pemasangan.md
      - Model: model.md
  - Code: reference/SUMMARY.md
