[tool.poetry]
name = "samudra"
version = "1.1.0"
description = ""
authors = ["Thaza_Kun <61819672+Thaza-Kun@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
peewee = "^3.15.0"
pytomlpp = "^1.0.11"
bind = "^2.1.0"
self = "^2020.12.3"
pydantic = "^1.9.1"
fastapi = "^0.79.0"
uvicorn = "^0.18.2"
pandas = "^1.4.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
